const canvas=document.getElementById('canvas'),wrap=document.getElementById('wrap'),ctx=canvas.getContext('2d'),statusEl=document.getElementById('status');
const CSS_PX_PER_MM=96/25.4;
let tool='line',start=null,shapes=[],selected=-1,zoomFactor=1,panX=0,panY=0;

function modelScale(){return CSS_PX_PER_MM*zoomFactor}
function screenToModel(x,y){const s=modelScale();return{x:(x-panX)/s,y:(y-panY)/s}}
function modelToScreen(x,y){const s=modelScale();return{x:panX+x*s,y:panY+y*s}}
function resize(){const dpr=window.devicePixelRatio||1,r=wrap.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';draw()}
addEventListener('resize',resize);
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;start=null});
function gridMM(){return Math.max(.1,+document.getElementById('grid-size').value||5)}
function snap(v){const g=gridMM();return Math.round(v/g)*g}
function pt(e){const r=canvas.getBoundingClientRect(),p=screenToModel(e.clientX-r.left,e.clientY-r.top);return{x:snap(p.x),y:snap(p.y)}}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function drawGrid(){const dpr=window.devicePixelRatio||1,w=canvas.width/dpr,h=canvas.height/dpr,g=gridMM(),s=modelScale();ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1/(dpr*zoomFactor);const a=screenToModel(0,0),b=screenToModel(w,h);for(let x=Math.floor(a.x/g)*g;x<=b.x;x+=g){ctx.beginPath();ctx.moveTo(x*s,Math.min(a.y,b.y)*s);ctx.lineTo(x*s,Math.max(a.y,b.y)*s);ctx.stroke()}for(let y=Math.floor(a.y/g)*g;y<=b.y;y+=g){ctx.beginPath();ctx.moveTo(Math.min(a.x,b.x)*s,y*s);ctx.lineTo(Math.max(a.x,b.x)*s,y*s);ctx.stroke()}}
function drawShape(s,i){ctx.strokeStyle=i===selected?'#2563eb':'#1e293b';ctx.fillStyle='#1e293b';ctx.lineWidth=(i===selected?3:2)/zoomFactor;if(s.t==='line'||s.t==='dim'){ctx.beginPath();ctx.moveTo(s.a.x*CSS_PX_PER_MM,s.a.y*CSS_PX_PER_MM);ctx.lineTo(s.b.x*CSS_PX_PER_MM,s.b.y*CSS_PX_PER_MM);ctx.stroke();if(s.t==='dim'){ctx.font=(12/zoomFactor)+'px Arial';ctx.fillText(dist(s.a,s.b).toFixed(2)+' mm',(s.a.x+s.b.x)/2*CSS_PX_PER_MM+4/zoomFactor,(s.a.y+s.b.y)/2*CSS_PX_PER_MM-4/zoomFactor)}}else if(s.t==='rect')ctx.strokeRect(s.a.x*CSS_PX_PER_MM,s.a.y*CSS_PX_PER_MM,(s.b.x-s.a.x)*CSS_PX_PER_MM,(s.b.y-s.a.y)*CSS_PX_PER_MM);else if(s.t==='circle'){ctx.beginPath();ctx.arc(s.a.x*CSS_PX_PER_MM,s.a.y*CSS_PX_PER_MM,dist(s.a,s.b)*CSS_PX_PER_MM,0,Math.PI*2);ctx.stroke()}else if(s.t==='label'){ctx.font=(14/zoomFactor)+'px Arial';ctx.fillText(s.text,s.a.x*CSS_PX_PER_MM,s.a.y*CSS_PX_PER_MM)}}
function draw(){const dpr=window.devicePixelRatio||1;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.translate(panX,panY);ctx.scale(zoomFactor,zoomFactor);drawGrid();shapes.forEach(drawShape)}
function hit(p){const tol=8/modelScale();for(let i=shapes.length-1;i>=0;i--){const s=shapes[i];if(s.t==='label'&&dist(p,s.a)<tol*3)return i;if(s.t==='circle'&&Math.abs(dist(p,s.a)-dist(s.a,s.b))<tol)return i;if(s.t==='rect'&&p.x>=Math.min(s.a.x,s.b.x)-tol&&p.x<=Math.max(s.a.x,s.b.x)+tol&&p.y>=Math.min(s.a.y,s.b.y)-tol&&p.y<=Math.max(s.a.y,s.b.y)+tol)return i;if(s.t==='line'||s.t==='dim'){const A=s.a,B=s.b,l2=(B.x-A.x)**2+(B.y-A.y)**2;let t=l2?((p.x-A.x)*(B.x-A.x)+(p.y-A.y)*(B.y-A.y))/l2:0;t=Math.max(0,Math.min(1,t));if(dist(p,{x:A.x+t*(B.x-A.x),y:A.y+t*(B.y-A.y)})<tol)return i}}return -1}
canvas.onmousedown=e=>{const p=pt(e);if(tool==='select'){selected=hit(p);draw();return}if(tool==='label'){const text=prompt('Label text:','');if(text){shapes.push({t:'label',a:p,text});draw()}return}start=p};
canvas.onmouseup=e=>{if(!start)return;const p=pt(e),map={line:'line',rect:'rect',circle:'circle',dimension:'dim'};if(map[tool])shapes.push({t:map[tool],a:start,b:p});start=null;draw()};
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,before=screenToModel(mx,my);zoomFactor=Math.max(.1,Math.min(20,zoomFactor*Math.exp(-e.deltaY*.001)));panX=mx-before.x*modelScale();panY=my-before.y*modelScale();draw()},{passive:false});
let panDrag=null;canvas.addEventListener('pointerdown',e=>{if(e.button===1||e.altKey){panDrag={x:e.clientX,y:e.clientY,px:panX,py:panY};canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(panDrag){panX=panDrag.px+e.clientX-panDrag.x;panY=panDrag.py+e.clientY-panDrag.y;draw()}});canvas.addEventListener('pointerup',()=>panDrag=null);
addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected>=0){shapes.splice(selected,1);selected=-1;draw()}});
document.getElementById('save').onclick=()=>{localStorage.setItem('ung-cad-2d',JSON.stringify({version:2,units:'mm',name:document.getElementById('drawing-name').value,shapes}));statusEl.textContent='Saved locally in mm model space.'};
document.getElementById('export').onclick=()=>{let svg='<svg xmlns="http://www.w3.org/2000/svg">';for(const s of shapes){if(s.t==='line'||s.t==='dim')svg+=`<line x1="${s.a.x}mm" y1="${s.a.y}mm" x2="${s.b.x}mm" y2="${s.b.y}mm" stroke="#111"/>`;else if(s.t==='rect')svg+=`<rect x="${Math.min(s.a.x,s.b.x)}mm" y="${Math.min(s.a.y,s.b.y)}mm" width="${Math.abs(s.b.x-s.a.x)}mm" height="${Math.abs(s.b.y-s.a.y)}mm" fill="none" stroke="#111"/>`;else if(s.t==='circle')svg+=`<circle cx="${s.a.x}mm" cy="${s.a.y}mm" r="${dist(s.a,s.b)}mm" fill="none" stroke="#111"/>`;else if(s.t==='label')svg+=`<text x="${s.a.x}mm" y="${s.a.y}mm">${s.text.replace(/[&<>]/g,'')}</text>`}svg+='</svg>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download=(document.getElementById('drawing-name').value||'drawing')+'.svg';a.click();statusEl.textContent='SVG exported with mm geometry.'};
try{const saved=JSON.parse(localStorage.getItem('ung-cad-2d')||'null');if(saved&&saved.version===2){shapes=saved.shapes||[];document.getElementById('drawing-name').value=saved.name||'Untitled'}}catch{}
window.__ung2dViewport={screenToModel,modelToScreen,get zoom(){return zoomFactor},get pan(){return{x:panX,y:panY}}};resize();