const canvas=document.getElementById('canvas'),wrap=document.getElementById('wrap'),ctx=canvas.getContext('2d'),statusEl=document.getElementById('status');
let tool='line',start=null,shapes=[],selected=-1;
function resize(){canvas.width=wrap.clientWidth;canvas.height=wrap.clientHeight;draw()}
addEventListener('resize',resize);
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;start=null});
function grid(){return Math.max(1,+document.getElementById('grid-size').value||20)}
function snap(v){const g=grid();return Math.round(v/g)*g}
function pt(e){const r=canvas.getBoundingClientRect();return{x:snap((e.clientX-r.left)*canvas.width/r.width),y:snap((e.clientY-r.top)*canvas.height/r.height)}}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function drawGrid(){ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;const g=grid();for(let x=0;x<canvas.width;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function drawShape(s,i){ctx.strokeStyle=i===selected?'#2563eb':'#1e293b';ctx.fillStyle='#1e293b';ctx.lineWidth=i===selected?3:2;if(s.t==='line'||s.t==='dim'){ctx.beginPath();ctx.moveTo(s.a.x,s.a.y);ctx.lineTo(s.b.x,s.b.y);ctx.stroke();if(s.t==='dim'){const scale=+document.getElementById('scale').value||.05;ctx.font='12px Arial';ctx.fillText((dist(s.a,s.b)*scale).toFixed(2)+' m',(s.a.x+s.b.x)/2+4,(s.a.y+s.b.y)/2-4)}}else if(s.t==='rect')ctx.strokeRect(s.a.x,s.a.y,s.b.x-s.a.x,s.b.y-s.a.y);else if(s.t==='circle'){ctx.beginPath();ctx.arc(s.a.x,s.a.y,dist(s.a,s.b),0,Math.PI*2);ctx.stroke()}else if(s.t==='label'){ctx.font='14px Arial';ctx.fillText(s.text,s.a.x,s.a.y)}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawGrid();shapes.forEach(drawShape)}
function hit(p){for(let i=shapes.length-1;i>=0;i--){const s=shapes[i];if(s.t==='label'&&dist(p,s.a)<25)return i;if(s.t==='circle'&&Math.abs(dist(p,s.a)-dist(s.a,s.b))<8)return i;if(s.t==='rect'&&p.x>=Math.min(s.a.x,s.b.x)-7&&p.x<=Math.max(s.a.x,s.b.x)+7&&p.y>=Math.min(s.a.y,s.b.y)-7&&p.y<=Math.max(s.a.y,s.b.y)+7)return i;if(s.t==='line'||s.t==='dim'){const A=s.a,B=s.b,l2=(B.x-A.x)**2+(B.y-A.y)**2;let t=l2?((p.x-A.x)*(B.x-A.x)+(p.y-A.y)*(B.y-A.y))/l2:0;t=Math.max(0,Math.min(1,t));if(dist(p,{x:A.x+t*(B.x-A.x),y:A.y+t*(B.y-A.y)})<8)return i}}return -1}
canvas.onmousedown=e=>{const p=pt(e);if(tool==='select'){selected=hit(p);draw();return}if(tool==='label'){const text=prompt('Label text:','');if(text){shapes.push({t:'label',a:p,text});draw()}return}start=p};
canvas.onmouseup=e=>{if(!start)return;const p=pt(e),map={line:'line',rect:'rect',circle:'circle',dimension:'dim'};if(map[tool])shapes.push({t:map[tool],a:start,b:p});start=null;draw()};
addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected>=0){shapes.splice(selected,1);selected=-1;draw()}});
document.getElementById('save').onclick=()=>{const data={name:document.getElementById('drawing-name').value,shapes};localStorage.setItem('ung-cad-2d',JSON.stringify(data));statusEl.textContent='Saved locally.'};
document.getElementById('export').onclick=()=>{let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${canvas.width}" height="${canvas.height}">`;for(const s of shapes){if(s.t==='line'||s.t==='dim')svg+=`<line x1="${s.a.x}" y1="${s.a.y}" x2="${s.b.x}" y2="${s.b.y}" stroke="#111"/>`;else if(s.t==='rect')svg+=`<rect x="${Math.min(s.a.x,s.b.x)}" y="${Math.min(s.a.y,s.b.y)}" width="${Math.abs(s.b.x-s.a.x)}" height="${Math.abs(s.b.y-s.a.y)}" fill="none" stroke="#111"/>`;else if(s.t==='circle')svg+=`<circle cx="${s.a.x}" cy="${s.a.y}" r="${dist(s.a,s.b)}" fill="none" stroke="#111"/>`;else if(s.t==='label')svg+=`<text x="${s.a.x}" y="${s.a.y}">${s.text.replace(/[&<>]/g,'')}</text>`}svg+='</svg>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download=(document.getElementById('drawing-name').value||'drawing')+'.svg';a.click();statusEl.textContent='SVG exported.'};
try{const saved=JSON.parse(localStorage.getItem('ung-cad-2d')||'null');if(saved){shapes=saved.shapes||[];document.getElementById('drawing-name').value=saved.name||'Untitled'}}catch{}
resize();

const BRIDGE_URL='http://127.0.0.1:8765';let lastCncDownload=null;
function cncSettings(){return{mode:document.getElementById('cnc-mode').value,scale_mm_per_px:parseFloat(document.getElementById('cnc-scale').value)||1,feed_rate:parseFloat(document.getElementById('cnc-feed').value)||800,plunge_rate:200,safe_z:parseFloat(document.getElementById('cnc-safez').value)||5,cut_depth_per_pass:parseFloat(document.getElementById('cnc-depth-pass').value)||1,total_depth:parseFloat(document.getElementById('cnc-total-depth').value)||1,spindle_speed:parseInt(document.getElementById('cnc-power').value)||12000,laser_power_percent:parseFloat(document.getElementById('cnc-power').value)||80}}
document.getElementById('cnc-generate').onclick=async()=>{const status=document.getElementById('cnc-status'),drawingName=document.getElementById('drawing-name').value||'drawing';if(!shapes.length){status.textContent='Nothing to export — draw something first.';return}status.textContent='Generating G-code…';try{const r=await fetch('/api/manufacturing/cnc-slice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shapes,drawing_name:drawingName,settings:cncSettings()})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'G-code generation failed');lastCncDownload=j.download;document.getElementById('cnc-send').disabled=false;status.textContent='G-CODE READY — '+j.stats.paths+' cut path(s), ~'+j.stats.estimated_seconds+'s estimated.\n';const a=document.createElement('a');a.href=j.download;a.download=j.machine_file;a.textContent='Download G-code';a.style.color='#59d6e7';status.appendChild(a)}catch(e){status.textContent='FAILED — '+e.message}};
async function bridgeHealth(){const r=await fetch(BRIDGE_URL+'/health',{cache:'no-store'});if(!r.ok)throw new Error('Bridge HTTP '+r.status);return await r.json()}
document.getElementById('cnc-refresh-ports').onclick=async()=>{const status=document.getElementById('cnc-send-status'),sel=document.getElementById('cnc-port');status.textContent='Checking local bridge for USB ports…';try{await bridgeHealth();const r=await fetch(BRIDGE_URL+'/serial/ports'),j=await r.json();if(j.error)throw new Error(j.error);sel.innerHTML='';if(!j.ports.length){sel.innerHTML='<option value="">No USB devices found</option>';status.textContent='No serial devices detected — check the machine is plugged in and powered on.';return}j.ports.forEach(p=>{const o=document.createElement('option');o.value=p.device;o.textContent=p.device+' — '+p.description;sel.appendChild(o)});status.textContent='Found '+j.ports.length+' port(s).'}catch(e){status.textContent='Bridge not reachable — download and run the local bridge first ('+e.message+')'}};
document.getElementById('cnc-send').onclick=async()=>{const status=document.getElementById('cnc-send-status'),port=document.getElementById('cnc-port').value,baud=document.getElementById('cnc-baud').value||'115200';if(!lastCncDownload){status.textContent='Generate G-code first.';return}if(!port){status.textContent='Select a USB port first (Refresh USB ports).';return}status.textContent='Sending G-code to machine…';try{const gcode=await(await fetch(lastCncDownload)).text();const r=await fetch(BRIDGE_URL+'/serial/send',{method:'POST',headers:{'X-Port':port,'X-Baud':baud},body:gcode}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Machine rejected job');status.textContent='JOB SENT — '+j.sent_lines+' G-code lines transmitted.'}catch(e){status.textContent='SEND FAILED — '+e.message}};
