(function(){
function n(id){return Number(document.getElementById(id).value)}
function calc(){
 const v1=n('em-v1'),n1=n('em-n1'),n2=n('em-n2'),f=n('em-freq'),area=n('em-core-area'),limit=n('em-bmax-limit'),i2=n('em-i2'),wire=n('em-wire-area'),turnLen=n('em-turn-length'),material=document.getElementById('em-core-material').value,coreVol=n('em-core-volume'),ambient=n('em-ambient'),thermalR=n('em-thermal-r'),out=document.getElementById('em-result');
 if(!(v1>=0&&n1>0&&n2>0&&f>0&&area>0&&limit>0&&wire>0&&turnLen>0&&coreVol>0&&thermalR>0)){out.innerHTML='<div class="danger">Enter positive turns and frequency.</div>';return}
 const ratio=n2/n1,v2=v1*ratio,type=ratio>1?'step-up':ratio<1?'step-down':'isolation / 1:1',areaM2=area*1e-4,bmax=v1/(4.44*f*n1*areaM2),j=i2/wire,lengthM=n2*turnLen/1000,rho=1.724e-8,resistance=rho*lengthM/(wire*1e-6),copperLoss=i2*i2*resistance,sat=bmax>limit,coreLossDensity=material==='silicon_steel'?0.0015*Math.pow(f/60,1.5)*Math.pow(Math.max(bmax,0.01),2):material==='ferrite'?0.00025*Math.pow(f/1000,1.6)*Math.pow(Math.max(bmax,0.01),2.3):0,coreLoss=coreLossDensity*coreVol,totalLoss=copperLoss+coreLoss,pout=v2*i2,eff=pout>0?100*pout/(pout+totalLoss):0,tempRise=totalLoss*thermalR,estimatedTemp=ambient+tempRise,regulation=pout>0?100*copperLoss/pout:0;
 out.innerHTML='<div><strong>V₂ ≈ '+v2.toFixed(2)+' V</strong></div><div class="muted">N₂/N₁ '+ratio.toFixed(4)+' · '+type+' · '+f.toFixed(1)+' Hz</div><div class="'+(sat?'danger':'muted')+'">Flux density ≈ '+bmax.toFixed(3)+' T · limit '+limit.toFixed(2)+' T · '+(sat?'SATURATION RISK':'within entered limit')+'</div><div class="muted">Secondary current density ≈ '+j.toFixed(2)+' A/mm² · R₂ ≈ '+resistance.toFixed(3)+' Ω · copper loss ≈ '+copperLoss.toFixed(2)+' W</div><div class="muted">Core loss ≈ '+coreLoss.toFixed(2)+' W · total modeled loss ≈ '+totalLoss.toFixed(2)+' W · efficiency ≈ '+eff.toFixed(1)+'%</div><div class="muted">Estimated temperature ≈ '+estimatedTemp.toFixed(1)+' °C (rise '+tempRise.toFixed(1)+' °C) · resistive regulation proxy ≈ '+regulation.toFixed(2)+'%</div><div class="muted">Preliminary engineering model only. Generic material coefficients are not a substitute for a core manufacturer loss curve; leakage, insulation class, airflow and hot spots require validation.</div>';
 window.dispatchEvent(new CustomEvent('ung:electromagnetics',{detail:{v1,n1,n2,frequency:f,ratio,v2,type,bmax,bmaxLimit:limit,saturationRisk:sat,currentDensity:j,resistance,copperLoss,coreLoss,totalLoss,efficiency:eff,tempRise,estimatedTemp,regulation,material}}));
}
document.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('em-calc-btn');if(b)b.addEventListener('click',calc);});
})();